language: python
python:
#  - "2.7"
#  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
#  - "pypy3"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt -r test-requirements.txt
before_script:
#  - flake8 --ignore=E501,W601,D203,D105 tsmppt60_driver
script:
  - coverage run --source=solar_monitor setup.py test
after_success:
  - coveralls
